### ISSUE TITLE
Doesn't install most of the drivers needed

### ISSUE THREAD

**Issue by coreycusick** [woa-msmnile/OnePlus-SM8150-DriverModule#8]
The driver updater installs the Qualcomm drivers over the OnePlus Drivers. I cannot install a GPU driver, audio drivers, modem driver, no usb, battery. I have redone the entire process repeatedly. No change at all

**Comment by NetuserPRO** [comment]
Hi, can you provide:
Where did you get your uefi image from?
Driver package you're using (msmnile-Drivers-Desktop-OnePlus.7z, or the current unstable ones in the github repository)
Which DriverUpdater version did you use?
Are you using Secure Boot (test signing on or off, SB or NOSB)?

**Comment by coreycusick** [comment]
image came from the Actions repo in the actions page in the repo, github repo as I wasn't aware of the .7z one, latest version, test signing on, secure boot should be off.

I did reflash OOS11 firmware, I will try the .7z one and report back

**Comment by NetuserPRO** [comment]
> image came from the actions page in the repo

Which repository?

> if you can tell me where to find that

In the telegram channel for onepluswoa, temporarily.
